export const DEPARTMENTS_LOADED = 'DEPARTMENTS_LOADED';
export const DEPARTMENT_DELETED = 'DEPARTMENT_DELETED';

export const EMPLOYEES_LOADED = 'EMPLOYEES_LOADED';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';
export const EMPLOYEE_DELETED = 'EMPLOYEE_DELETED';
